#!/bin/bash
# Greed Machine Installer - maintained by Gidz Cross
# Automated Installer for rAthena orginally by Akkarin
# Made for Debian OS
# General
DEV=0
INSTALLER_VERSION="v1.0"
STEPS=11
# Colors
BLUE='\033[0;36m'
GREEN='\033[0;92m'
YELLOW='\033[0;93m'
NC='\033[0m'

# Credentials
USERID=$(date +%s | sha256sum | base64 | head -c 3 ; echo)
USERPASS=$(date +%s | sha256sum | base64 | head -c 6 ; echo)
RATHENAPASS="gidzdlcrz"
RAGSQLPASS=$(date +%s | sha256sum | base64 | head -c 10 ; echo)

# URLs
URL_RA="https://rathena.org/board"
URL_RAGIT="https://github.com/rathena/rathena"
URL_FLUXGIT="https://github.com/rathena/FluxCP"
SERVER_IPLIST=$(ip addr|awk '/eth0/ && /inet/ {gsub(/\/[0-9][0-9]/,""); print $2}')
SERVER_IP=$(echo $SERVER_IPLIST | cut -d ' ' -f 1 )

if [ $DEV -eq 1 ]
then
	VERSION="${INSTALLER_VERSION} - ${YELLOW}Development Script${NC}"
else
	VERSION="${INSTALLER_VERSION}"
fi

echo "\033c"
echo "Welcome to ${BLUE}Greed Machine${NC}, an unattended installer by Gidz Cross"
echo "Version: ${VERSION}\n"
echo "The script will now begin to install stuff on your system. Please be patient as this could take a while!\n"


echo "${BLUE}Step 1/${STEPS}:${NC} Updating your OS"
apt-get -qy update > /dev/null
apt-get -qy upgrade > /dev/null
echo ""


echo "${BLUE}Step 2/${STEPS}:${NC} Installing Prerequisites"
apt-get -qy install expect wget sudo > /dev/null
echo ""


echo "${BLUE}Step 3/${STEPS}:${NC} Installing MySQL Stuff"
apt-get -qy install libaio1 libdbd-mariadb-perl libdbi-perl libterm-readkey-perl libhtml-template-perl > /dev/null
export DEBIAN_FRONTEND=noninteractive 
bash -c 'debconf-set-selections <<< "mariadb-server mariadb-server/root_password password ragnarok"'
bash -c 'debconf-set-selections <<< "mariadb-server mariadb-server/root_password_again password ragnarok"'

apt-get -qy install mariadb-server
wget -q https://raw.githubusercontent.com/gamingmagic/unattended-installer/master/msi.sh
chmod +x msi.sh
./msi.sh
rm msi.sh


echo "${BLUE}Step 4/${STEPS}:${NC} Installing Apache2 & PHP"
echo " * Installing Apache2"
apt-get -qy install apache2 > /dev/null
echo " * Installing PHP"
apt-get -qy install libapache2-mod-php php-mysql php-gd php-mbstring php-xml > /dev/null
systemctl restart apache2
echo ""


echo "${BLUE}Step 5/${STEPS}:${NC} Installing rA specific packages"
echo " * Installing git, make, g++"
apt-get -qy install git make libmariadb-dev libmariadbclient-dev libmariadbclient-dev-compat > /dev/null
echo " * Installing Utilities"
apt-get -qy install zlib1g-dev libpcre3-dev nano zip unzip zenity gcc g++ > /dev/null
echo ""


echo "${BLUE}Step 6/${STEPS}:${NC} Creating User: rathena"
echo "${YELLOW}This process is automatic and doesn't require user input.${NC}"
echo "${YELLOW}Please do not type at the password prompt.${NC}"
wget -q https://github.com/gamingmagic/unattended-installer/raw/master/createuser.zip
unzip -qq createuser.zip
chmod +x createuser.sh
./createuser.sh $RATHENAPASS
rm createuser.sh
gpasswd -a rathena sudo
echo ""


echo "${BLUE}Step 7/${STEPS}:${NC} Creating MySQL Database"
mysqladmin -u root -pragnarok create ragnarok
mysql -u root -pragnarok -e "CREATE USER ragnarok@localhost IDENTIFIED BY 'gidzdlcrz';"
mysql -u root -pragnarok -e "GRANT ALL PRIVILEGES ON ragnarok.* TO 'ragnarok'@'localhost';"
mysql -u root -pragnarok -e "FLUSH PRIVILEGES;"
mysql -u root -pragnarok ragnarok  < /home/rathena/Desktop/rAthena/sql-files/main.sql
mysql -u root -pragnarok ragnarok  < /home/rathena/Desktop/rAthena/sql-files/logs.sql
mysql -u root -pragnarok ragnarok  < /home/rathena/Desktop/rAthena/sql-files/item_cash_db.sql
mysql -u root -pragnarok ragnarok  < /home/rathena/Desktop/rAthena/sql-files/item_cash_db2.sql
mysql -u root -pragnarok ragnarok  < /home/rathena/Desktop/rAthena/sql-files/item_db.sql
mysql -u root -pragnarok ragnarok  < /home/rathena/Desktop/rAthena/sql-files/item_db2.sql
mysql -u root -pragnarok ragnarok  < /home/rathena/Desktop/rAthena/sql-files/item_db2_re.sql
mysql -u root -pragnarok ragnarok  < /home/rathena/Desktop/rAthena/sql-files/item_db_re.sql
mysql -u root -pragnarok ragnarok  < /home/rathena/Desktop/rAthena/sql-files/mob_db.sql
mysql -u root -pragnarok ragnarok  < /home/rathena/Desktop/rAthena/sql-files/mob_db2.sql
mysql -u root -pragnarok ragnarok  < /home/rathena/Desktop/rAthena/sql-files/mob_db2_re.sql
mysql -u root -pragnarok ragnarok  < /home/rathena/Desktop/rAthena/sql-files/mob_db_re.sql
mysql -u root -pragnarok ragnarok  < /home/rathena/Desktop/rAthena/sql-files/mob_skill_db.sql
mysql -u root -pragnarok ragnarok  < /home/rathena/Desktop/rAthena/sql-files/mob_skill_db2.sql
mysql -u root -pragnarok ragnarok  < /home/rathena/Desktop/rAthena/sql-files/mob_skill_db2_re.sql
mysql -u root -pragnarok ragnarok  < /home/rathena/Desktop/rAthena/sql-files/mob_skill_db_re.sql
mysql -u root -pragnarok -e "USE ragnarok; UPDATE login SET userid = '${USERID}', user_pass = 'gidzdlcrz' where sex = 'S';"
echo ""



echo "${BLUE}Step 8/${STEPS}:${NC} Configuring FluxCP"
rm /var/www/html/index.html
git clone -q ${URL_FLUXGIT} /var/www/html/
cd /var/www/html/
wget -q https://raw.githubusercontent.com/gamingmagic/unattended-installer/master/diff.diff
echo "diff --git a/config/application.php b/config/application.php" >> /var/www/html/diff.diff
echo "--- a/config/application.php" >> /var/www/html/diff.diff
echo "+++ b/config/application.php" >> /var/www/html/diff.diff
echo "@@ -3,7 +3,7 @@" >> /var/www/html/diff.diff
echo " // the default, and should be changed as needed." >> /var/www/html/diff.diff
echo " return array(" >> /var/www/html/diff.diff
echo " 	'ServerAddress'				=> 'localhost',				// This value is the hostname:port under which Flux runs. (e.g., example.com or example.com:80)" >> /var/www/html/diff.diff
echo "-	'BaseURI'					=> 'fluxcp',						// The base URI is the base web root on which your application lies." >> /var/www/html/diff.diff
echo "+	'BaseURI'					=> '',						// The base URI is the base web root on which your application lies." >> /var/www/html/diff.diff
echo " 	'InstallerPassword'			=> 'secretpassword',		// Installer/updater password." >> /var/www/html/diff.diff
echo " 	'RequireOwnership'			=> true,					// Require the executing user to be owner of the FLUX_ROOT/data/ directory tree? (Better for security)" >> /var/www/html/diff.diff
echo " 															// WARNING: This will be mostly IGNORED on non-POSIX-compliant OSes (e.g. Windows)." >> /var/www/html/diff.diff
echo "diff --git a/config/servers.php b/config/servers.php" >> /var/www/html/diff.diff
echo "--- a/config/servers.php" >> /var/www/html/diff.diff
echo "+++ b/config/servers.php" >> /var/www/html/diff.diff
echo "@@ -15,7 +15,7 @@ return array(" >> /var/www/html/diff.diff
echo " 				// -- It specifies the encoding to convert your MySQL data to on the website (most likely needs to be utf8)" >> /var/www/html/diff.diff
echo " 			'Hostname'   => '127.0.0.1'," >> /var/www/html/diff.diff
echo " 			'Username'   => 'ragnarok'," >> /var/www/html/diff.diff
echo "-			'Password'   => 'ragnarok'," >> /var/www/html/diff.diff
echo "+			'Password'   => 'gidzdlcrz'," >> /var/www/html/diff.diff
echo " 			'Database'   => 'ragnarok'," >> /var/www/html/diff.diff
echo " 			'Persistent' => true," >> /var/www/html/diff.diff
echo " 			'Timezone'   => null // Example: '+0:00' is UTC." >> /var/www/html/diff.diff
echo "@@ -36,7 +36,7 @@ return array(" >> /var/www/html/diff.diff
echo " 				// -- It specifies the encoding to convert your MySQL data to on the website (most likely needs to be utf8)" >> /var/www/html/diff.diff
echo " 			'Hostname'   => '127.0.0.1'," >> /var/www/html/diff.diff
echo " 			'Username'   => 'ragnarok'," >> /var/www/html/diff.diff
echo "-			'Password'   => 'ragnarok'," >> /var/www/html/diff.diff
echo "+			'Password'   => 'gidzdlcrz'," >> /var/www/html/diff.diff
echo " 			'Database'   => 'ragnarok'," >> /var/www/html/diff.diff
echo " 			'Persistent' => true," >> /var/www/html/diff.diff
echo " 			'Timezone'   => null // Possible values is as described in the comment in DbConfig." >> /var/www/html/diff.diff
git apply diff.diff
rm /var/www/html/diff.diff
usermod -a -G www-data rathena
chown -R www-data:www-data /var/www/html
chmod -R 0774 /var/www/html
ln -s /var/www/html /home/rathena/Desktop/FluxCP
echo ""



echo "${BLUE}Step 9/${STEPS}:${NC} Installing phpMyAdmin"
wget -q https://files.phpmyadmin.net/phpMyAdmin/4.7.3/phpMyAdmin-4.7.3-english.zip
unzip -qq phpMyAdmin-4.7.3-english.zip
rm phpMyAdmin-4.7.3-english.zip
mv phpMyAdmin-4.7.3-english phpmyadmin
cd phpmyadmin
mv config.sample.inc.php config.inc.php
echo "<?php" > /var/www/html/phpmyadmin/config.inc.php
BLOWFISH=$(date +%s | sha256sum | base64 | head -c 32 ; echo)
echo "\$cfg['blowfish_secret'] = '${BLOWFISH}';" >> /var/www/html/phpmyadmin/config.inc.php
echo "\$i=0;" >> /var/www/html/phpmyadmin/config.inc.php
echo "\$i++;" >> /var/www/html/phpmyadmin/config.inc.php
echo "\$cfg['Servers'][\$i]['host'] = 'localhost';" >> /var/www/html/phpmyadmin/config.inc.php
echo "\$cfg['Servers'][\$i]['AllowRoot'] = false;" >> /var/www/html/phpmyadmin/config.inc.php
echo "\$cfg['Servers'][\$i]['AllowNoPassword'] = false;" >> /var/www/html/phpmyadmin/config.inc.php
echo "\$cfg['Servers'][\$i]['auth_type']     = 'cookie';" >> /var/www/html/phpmyadmin/config.inc.php
chown -R www-data:www-data /var/www/html
chmod 0660 /var/www/html/phpmyadmin/config.inc.php
echo ""


cd /var/www/html/data/schemas/logindb/
wget -q https://raw.githubusercontent.com/gamingmagic/unattended-installer/master/cp_cmspages.20170808161901.sql
chown -R www-data:www-data /var/www/html
cd /home/



echo "${BLUE}Step 10/${STEPS}:${NC} Preparing auto-config import files"
echo "//fenrirmachine\n" >> /home/rathena/Desktop/rAthena/conf/import-tmpl/char_conf.txt
echo "userid: ${USERID}" >> /home/rathena/Desktop/rAthena/conf/import-tmpl/char_conf.txt
echo "passwd: gidzdlcrz" >> /home/rathena/Desktop/rAthena/conf/import-tmpl/char_conf.txt
echo "char_ip: ${SERVER_IP}" >> /home/rathena/Desktop/rAthena/conf/import-tmpl/char_conf.txt

echo "//fenrirmachine\n" >> /home/rathena/Desktop/rAthena/conf/import-tmpl/map_conf.txt
echo "userid: ${USERID}" >> /home/rathena/Desktop/rAthena/conf/import-tmpl/map_conf.txt
echo "passwd: gidzdlcrz" >> /home/rathena/Desktop/rAthena/conf/import-tmpl/map_conf.txt
echo "map_ip: ${SERVER_IP}" >> /home/rathena/Desktop/rAthena/conf/import-tmpl/map_conf.txt

echo "//fenrirmachine\n" >> /home/rathena/Desktop/rAthena/conf/import-tmpl/inter_conf.txt
echo "//use_sql_db: yes" >> /home/rathena/Desktop/rAthena/conf/import-tmpl/inter_conf.txt
echo "login_server_pw: gidzdlcrz" >> /home/rathena/Desktop/rAthena/conf/import-tmpl/inter_conf.txt
echo "ipban_db_pw: gidzdlcrz" >> /home/rathena/Desktop/rAthena/conf/import-tmpl/inter_conf.txt
echo "char_server_pw: gidzdlcrz" >> /home/rathena/Desktop/rAthena/conf/import-tmpl/inter_conf.txt
echo "map_server_pw: gidzdlcrz" >> /home/rathena/Desktop/rAthena/conf/import-tmpl/inter_conf.txt
echo "log_db_pw: gidzdlcrz" >> /home/rathena/Desktop/rAthena/conf/import-tmpl/inter_conf.txt
echo ""

touch /home/rathena/Desktop/Info.txt
echo "fenrirmachine\n" >> /home/rathena/Desktop/Info.txt
echo "Server IP: ${SERVER_IP}\n" >> /home/rathena/Desktop/Info.txt
echo "-- MySQL --" >> /home/rathena/Desktop/Info.txt
echo "root password is 'ragnarok', but can only be accessed locally from this system." >> /home/rathena/Desktop/Info.txt
echo "For all other MySQL uses, please use the following credentials:" >> /home/rathena/Desktop/Info.txt
echo "User: ragnarok" >> /home/rathena/Desktop/Info.txt
echo "Password: gidzdlcrz\n" >> /home/rathena/Desktop/Info.txt

echo "-- SSH User --" >> /home/rathena/Desktop/Info.txt
echo "User: rathena" >> /home/rathena/Desktop/Info.txt
echo "Password: $RATHENAPASS\n" >> /home/rathena/Desktop/Info.txt

echo "-- FluxCP --" >> /home/rathena/Desktop/Info.txt
echo " * Access FluxCP from this server using the browser and going to http://localhost" >> /home/rathena/Desktop/Info.txt
echo " or" >> /home/rathena/Desktop/Info.txt
echo " * Access FluxCP from anywhere by browsing to http://${SERVER_IP}/" >> /home/rathena/Desktop/Info.txt
echo "The Installer Password is the default for FluxCP, which is secretpassword\n" >> /home/rathena/Desktop/Info.txt

echo "-- phpMyAdmin --" >> /home/rathena/Desktop/Info.txt
echo " * Access phpMyAdmin from this server using the browser and going to http://localhost/phpmyadmin" >> /home/rathena/Desktop/Info.txt
echo " or" >> /home/rathena/Desktop/Info.txt
echo " * Access phpMyAdmin from anywhere by browsing to http://${SERVER_IP}/phpmyadmin" >> /home/rathena/Desktop/Info.txt
echo "Access from root user is disabled, so you will need to login as 'ragnarok' with your MySQL password.\n" >> /home/rathena/Desktop/Info.txt

echo "-- Full Client --" >> /home/rathena/Desktop/Info.txt
echo "A full client will be made available to you on your downloads page straight" >> /home/rathena/Desktop/Info.txt
echo " after completing the FluxCP installation process. This is located at:" >> /home/rathena/Desktop/Info.txt
echo " * URL: http://${SERVER_IP}/?module=pages&action=content&page=downloads" >> /home/rathena/Desktop/Info.txt
echo " * Filesystem: FluxCP Desktop Shortcut -> downloads folder" >> /home/rathena/Desktop/Info.txt



echo "${BLUE}Step 11/${STEPS}:${NC} Finishing up!"
echo ""
echo ""
echo ""
echo ""
echo "${YELLOW}*****************************************************************${NC}"
echo ""
echo "${BLUE}All done!${NC}"
echo "${GREEN} -- System Stuff${NC}"
echo "Linux User 'rathena' Password: ${RATHENAPASS}"
echo "Server IP: ${SERVER_IP}"
echo ""
echo "${GREEN} -- MySQL Stuff${NC}"
echo "MySQL user: ragnarok"
echo "MySQL password: gidzdlcrz"
echo "phpMyAdmin: http://${SERVER_IP}/phpmyadmin"
echo ""
echo "${GREEN} -- VNC Stuff${NC}"
echo "VNC Password: gidzdlcrz"

echo ""
echo "${GREEN} -- FluxCP Stuff${NC}"
echo "Control Panel: http://${SERVER_IP}/"
echo "After FluxCP installation, full installer will be available via your site."
rm /home/cerv
exit 0
