#!/bin/bash
# Greed Machine Installer - maintained by Gidz Cross
# installer rathena orginal by Akkarin
# General
DEV=0
INSTALLER_VERSION="v1.2.08"
STEPS=14
# Colors
BLUE='\033[0;36m'
GREEN='\033[0;92m'
YELLOW='\033[0;93m'
NC='\033[0m'

# Credentials
USERID=$(date +%s | sha256sum | base64 | head -c 3 ; echo)
USERPASS=$(date +%s | sha256sum | base64 | head -c 6 ; echo)
RATHENAPASS="gidzdlcrz"
RAGSQLPASS=$(date +%s | sha256sum | base64 | head -c 10 ; echo)

# URLs
URL_RA="https://rathena.org/board"
URL_RAGIT="https://github.com/rathena/rathena"
URL_FLUXGIT="https://github.com/rathena/FluxCP"
SERVER_IPLIST=$(ip addr|awk '/eth0/ && /inet/ {gsub(/\/[0-9][0-9]/,""); print $2}')
SERVER_IP=$(echo $SERVER_IPLIST | cut -d ' ' -f 1 )

if [ $DEV -eq 1 ]
then
	VERSION="${INSTALLER_VERSION} - ${YELLOW}Development Script${NC}"
else
	VERSION="${INSTALLER_VERSION}"
fi

echo "\033c"
echo "Welcome to ${BLUE}Greed Machine${NC}, an unattended installer by Gidz Cross"
echo "Version: ${VERSION}\n"
echo "This script will now begin to install stuff on your system. Please be patient as this could take a while!\n"

echo "${BLUE}Step 1/${STEPS}:${NC} Updating your OS"
apt-get -qy update > /dev/null
apt-get -qy upgrade > /dev/null
echo ""

echo "${BLUE}Step 2/${STEPS}:${NC} Installing Prerequisites"
apt-get -qy install expect wget sudo > /dev/null
echo ""

echo "${BLUE}Step 3/${STEPS}:${NC} Installing MySQL Stuff"
apt-get -qy install libaio1 libdbd-mariadb-perl libdbi-perl libterm-readkey-perl libhtml-template-perl > /dev/null
export DEBIAN_FRONTEND=noninteractive 
bash -c 'debconf-set-selections <<< "mariadb-server mariadb-server/root_password password ragnarok"'
bash -c 'debconf-set-selections <<< "mariadb-server mariadb-server/root_password_again password ragnarok"'
apt-get -qy install mariadb-server
echo ""

echo "${BLUE}Step 4/${STEPS}:${NC} Installing Apache2 & PHP"
echo " * Installing Apache2"
apt-get -qy install apache2 > /dev/null
echo " * Installing PHP"
apt-get -qy install libapache2-mod-php php-mysql php-gd php-mbstring php-xml > /dev/null
systemctl restart apache2
echo ""

echo "${BLUE}Step 5/${STEPS}:${NC} Installing rA specific packages"
echo " * Installing git, make, g++"
apt-get -qy install git make libmariadb-dev libmariadbclient-dev libmariadbclient-dev-compat > /dev/null
echo " * Installing Utilities"
apt-get -qy install zlib1g-dev libpcre3-dev nano zip unzip zenity gcc g++ > /dev/null
echo ""

echo "${BLUE}Step 6/${STEPS}:${NC} Creating User: rathena"
echo "${YELLOW}This process is automatic and doesn't require user input.${NC}"
echo "${YELLOW}Please do not type at the password prompt.${NC}"
wget -q https://github.com/gamingmagic/unattended-installer/raw/master/createuser.zip
unzip -qq createuser.zip
chmod +x createuser.sh
./createuser.sh $RATHENAPASS
rm createuser.sh
gpasswd -a rathena sudo
echo ""

echo "${BLUE}Step 8/${STEPS}:${NC} Setting Up MySQL Server"
echo " * Configuring MySQL Server"
service mysql restart
mysql_secure_installation <<EOF

y
$RATHENAPASS
$RATHENAPASS
y
y
y
y
EOF
echo ""

echo "${BLUE}Step 12/${STEPS}:${NC} Setting Up Flux Control Panel"
echo " * Downloading Flux Control Panel"
mkdir -p /home/rathena/fluxcp
cd /home/rathena/temp
git clone --depth=1 --branch=master $URL_FLUXGIT /home/rathena/temp/fluxcp
cp -R /home/rathena/temp/fluxcp/* /home/rathena/fluxcp
echo ""

echo "${BLUE}Step 13/${STEPS}:${NC} Setting Up rAthena Configuration Files"
echo " * Setting Up rAthena Configuration Files"
cd /home/rathena/conf
sed -i "s/usernamehere/$USERID/g" login_athena.conf
sed -i "s/passwordhere/$USERPASS/g" login_athena.conf
sed -i "s/ipaddresshere/$SERVER_IP/g" login_athena.conf
sed -i "s/passwordhere/$RAGSQLPASS/g" char_athena.conf
sed -i "s/passwordhere/$RAGSQLPASS/g" map_athena.conf
echo ""

echo "${BLUE}Step 15/${STEPS}:${NC} Installation Complete"
echo " * Your installation is complete!"
echo " * Visit your server at http://$SERVER_IP or http://$SERVER_IP/fluxcp"
echo " * Login: $USERID"
echo " * Password: $USERPASS"
echo " * MySQL Password: $RATHENAPASS"
echo " * MySQL rAthena Password: $RAGSQLPASS"
echo ""
